version: "3"
services:
    prisma:
        container_name: whisper_prisma_server
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - "4466:4466"
        environment:
            PRISMA_CONFIG: |
                # On console, for the prisma cli:
                # export PRISMA_MANAGEMENT_API_SECRET="dockerpass1234"
                managementApiSecret: dockerpass1234
                port: 4466
                databases:
                  default:
                    connector: postgres
                    host: postgres
                    port: 5432
                    user: prisma
                    password: prisma
    postgres:
        container_name: whisper_postgres_server
        image: postgres:10.3
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - postgres:/var/lib/postgresql/data
    redis:
        container_name: whisper_redis_server
        image: redis
        restart: always
        ports:
            - "6379:6379"
volumes:
    postgres: ~
