version: '3'
services:
  prisma:
    container_name: whisper_prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        # On console, for the Prisma cli:
        # export PRISMA_MANAGEMENT_API_SECRET="API_SECRET_20191227185837"
        managementApiSecret: API_SECRET_20191227185837
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    container_name: whisper_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    container_name: whisper_redis
    image: redis
    command: redis-server --requirepass RAN20191227185143PASS
    restart: always
    ports:
      - '6379:6379'
volumes:
  postgres: ~
